---
markdown: kramdown
highlighter: rouge
title: Eskander
tagline: Blog
description: A small blog where I write about Linux and Electronics tinkering.
url: https://eskander.github.io/
baseurl: ''
author:
  name: Eskander Bejaoui
  url: https://twitter.com/EskanderBejaoui
paginate: 5
exclude:
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: " UA-148324756-1 "
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
