---
markdown: kramdown
highlighter: rouge
title: Eskander
tagline: Eskander's Blog
description: The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme
  for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.
url: https://eskander.github.io/
baseurl: ''
author:
  name: Eskander Bejaoui
  url: https://twitter.com/EskanderBejaoui
paginate: 5
exclude:
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
